// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    return CV.listenMenu();
  });

  this.CV = {
    listenMenu: function() {
      return $("#main-menu li a").on("click", function() {
        return CV.activePage(this, $(this).parent("li"));
      });
    },
    activePage: function(elemFromEvent, parentElem) {
      var pageToActive;
      pageToActive = CV.retrievePageToActive(elemFromEvent);
      CV.hideOldActivePage();
      CV.unactiveOldMenu();
      CV.activeNewMenu(parentElem);
      return CV.showNewActivePage(pageToActive);
    },
    retrievePageToActive: function(elemFromEvent) {
      var hrefLinkValue, pageToActiveId;
      hrefLinkValue = $(elemFromEvent).attr("href").substring(1);
      pageToActiveId = "#page-" + hrefLinkValue;
      return pageToActiveId;
    },
    hideOldActivePage: function() {
      $(".content-pages div.on").addClass("off");
      return $(".content-pages div.on").removeClass("on");
    },
    unactiveOldMenu: function() {
      return $("#main-menu li.active").removeClass("active");
    },
    activeNewMenu: function(menuToActive) {
      return $(menuToActive).addClass("active");
    },
    showNewActivePage: function(pageToActive) {
      $(pageToActive).removeClass("off");
      return $(pageToActive).addClass("on");
    },
    /*listenTag : ->
      $(competences_selector).hover(
        -> CV.handlerIn(this),
        -> CV.handlerOut(this)
      )
    */

    handlerIn: function(elem) {
      var left;
      left = $(elem).position().left;
      $("#" + $(elem).attr("id") + "Div").show();
      $("#" + $(elem).attr("id") + "Div").offset({
        left: left - 20
      });
      $(elem).addClass("check");
      return $(".css-arrow-top").offset({
        left: left + 20
      });
    },
    handlerOut: function(elem) {
      $("#" + $(elem).attr("id") + "Div").hide();
      return $(elem).removeClass("check");
    },
    hideAllSubTitle: function() {
      return $("article h4 + ul").hide();
    },
    listenSubTitle: function() {
      return $(h4_article_selector).on("click", function() {
        var visible;
        visible = $(this).next("ul").css("display");
        if (visible === "none") {
          return CV.showSubTitle(this);
        } else {
          return CV.hideSubTitle(this);
        }
      });
    },
    showSubTitle: function(h4this) {
      return $(h4this).next("ul").show();
    },
    hideSubTitle: function(h4this) {
      return $(h4this).next("ul").hide();
    }
  };

}).call(this);
